repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check . --python .venv
        language: python
      - id: docs
        name: Generate Action docs
        entry: auto-doc --filename action.yml
        language: system
        pass_filenames: false
        always_run: true
