name: uv Lockfile Report

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Report
        uses: mw-root/uv-lock-report@30a5494eada8f15918ed765b773a84b29c2aa234 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
